/*
 * Veda Platform HTTP Interface
 *
 * API for interacting with the Veda platform services.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMultipleIndividualsRequest {
    /// The unique identifier of the user's ticket.
    #[serde(rename = "ticket")]
    pub ticket: String,
    /// An array of unique identifiers (URIs) of the individuals.
    #[serde(rename = "uris")]
    pub uris: Vec<String>,
    /// Optional flag to reopen the query.
    #[serde(rename = "reopen", skip_serializing_if = "Option::is_none")]
    pub reopen: Option<bool>,
}

impl GetMultipleIndividualsRequest {
    pub fn new(ticket: String, uris: Vec<String>) -> GetMultipleIndividualsRequest {
        GetMultipleIndividualsRequest {
            ticket,
            uris,
            reopen: None,
        }
    }
}

